services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: redis-refresh-token
    ports:
      - "3000:3000"
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - NEST_DEBUG=true
    depends_on:
      - database
      - redis
    restart: always
    command: npm run start:dev
    networks:
      - app_network
  
  database:
    image: postgres:10.17
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=maindb"
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: always
    networks:
      - app_network
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    networks:
      - app_network
    volumes:
      - redis-data:/data

volumes:
  pg-data:
    driver: local
  redis-data:

networks:
  app_network:
    driver: bridge
